import { z } from 'zod';
export declare const CriarProdutoSchema: z.ZodObject<{
    nome: z.ZodString;
    tipo: z.ZodEnum<["INSUMO", "PRODUTO_ACABADO", "INSUMO_PRODUTO"]>;
    categoriaId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    unidadeMedida: z.ZodDefault<z.ZodEnum<["KG", "G", "L", "ML", "UN", "CX", "PCT"]>>;
    estoqueMinimo: z.ZodDefault<z.ZodNumber>;
    custoUnitario: z.ZodDefault<z.ZodNumber>;
    precoVenda: z.ZodOptional<z.ZodNumber>;
    ncm: z.ZodUnion<[z.ZodOptional<z.ZodString>, z.ZodLiteral<"">]>;
    cest: z.ZodOptional<z.ZodString>;
    cfop: z.ZodUnion<[z.ZodOptional<z.ZodString>, z.ZodLiteral<"">]>;
    origem: z.ZodDefault<z.ZodNumber>;
    csosn: z.ZodOptional<z.ZodString>;
    cstICMS: z.ZodOptional<z.ZodString>;
    cstPIS: z.ZodOptional<z.ZodString>;
    cstCOFINS: z.ZodOptional<z.ZodString>;
    pICMS: z.ZodOptional<z.ZodNumber>;
    pPIS: z.ZodOptional<z.ZodNumber>;
    pCOFINS: z.ZodOptional<z.ZodNumber>;
    unidadeComercial: z.ZodOptional<z.ZodString>;
    gtin: z.ZodOptional<z.ZodString>;
    fornecedorId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    codigoFornecedor: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    fatorConversao: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    operacaoConversao: z.ZodNullable<z.ZodOptional<z.ZodEnum<["MULTIPLICAR", "DIVIDIR"]>>>;
}, "strip", z.ZodTypeAny, {
    nome: string;
    tipo: "INSUMO" | "PRODUTO_ACABADO" | "INSUMO_PRODUTO";
    unidadeMedida: "KG" | "G" | "L" | "ML" | "UN" | "CX" | "PCT";
    custoUnitario: number;
    estoqueMinimo: number;
    origem: number;
    categoriaId?: string | null | undefined;
    precoVenda?: number | undefined;
    ncm?: string | undefined;
    cest?: string | undefined;
    cfop?: string | undefined;
    csosn?: string | undefined;
    cstICMS?: string | undefined;
    cstPIS?: string | undefined;
    cstCOFINS?: string | undefined;
    pICMS?: number | undefined;
    pPIS?: number | undefined;
    pCOFINS?: number | undefined;
    unidadeComercial?: string | undefined;
    gtin?: string | undefined;
    fornecedorId?: string | null | undefined;
    codigoFornecedor?: string | null | undefined;
    fatorConversao?: number | null | undefined;
    operacaoConversao?: "MULTIPLICAR" | "DIVIDIR" | null | undefined;
}, {
    nome: string;
    tipo: "INSUMO" | "PRODUTO_ACABADO" | "INSUMO_PRODUTO";
    unidadeMedida?: "KG" | "G" | "L" | "ML" | "UN" | "CX" | "PCT" | undefined;
    custoUnitario?: number | undefined;
    categoriaId?: string | null | undefined;
    estoqueMinimo?: number | undefined;
    precoVenda?: number | undefined;
    ncm?: string | undefined;
    cest?: string | undefined;
    cfop?: string | undefined;
    origem?: number | undefined;
    csosn?: string | undefined;
    cstICMS?: string | undefined;
    cstPIS?: string | undefined;
    cstCOFINS?: string | undefined;
    pICMS?: number | undefined;
    pPIS?: number | undefined;
    pCOFINS?: number | undefined;
    unidadeComercial?: string | undefined;
    gtin?: string | undefined;
    fornecedorId?: string | null | undefined;
    codigoFornecedor?: string | null | undefined;
    fatorConversao?: number | null | undefined;
    operacaoConversao?: "MULTIPLICAR" | "DIVIDIR" | null | undefined;
}>;
export declare const AtualizarProdutoSchema: z.ZodObject<{
    nome: z.ZodOptional<z.ZodString>;
    tipo: z.ZodOptional<z.ZodEnum<["INSUMO", "PRODUTO_ACABADO", "INSUMO_PRODUTO"]>>;
    categoriaId: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    unidadeMedida: z.ZodOptional<z.ZodDefault<z.ZodEnum<["KG", "G", "L", "ML", "UN", "CX", "PCT"]>>>;
    estoqueMinimo: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    custoUnitario: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    precoVenda: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    ncm: z.ZodOptional<z.ZodUnion<[z.ZodOptional<z.ZodString>, z.ZodLiteral<"">]>>;
    cest: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    cfop: z.ZodOptional<z.ZodUnion<[z.ZodOptional<z.ZodString>, z.ZodLiteral<"">]>>;
    origem: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    csosn: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    cstICMS: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    cstPIS: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    cstCOFINS: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    pICMS: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    pPIS: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    pCOFINS: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    unidadeComercial: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    gtin: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    fornecedorId: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    codigoFornecedor: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    fatorConversao: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNumber>>>;
    operacaoConversao: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodEnum<["MULTIPLICAR", "DIVIDIR"]>>>>;
}, "strip", z.ZodTypeAny, {
    nome?: string | undefined;
    tipo?: "INSUMO" | "PRODUTO_ACABADO" | "INSUMO_PRODUTO" | undefined;
    unidadeMedida?: "KG" | "G" | "L" | "ML" | "UN" | "CX" | "PCT" | undefined;
    custoUnitario?: number | undefined;
    categoriaId?: string | null | undefined;
    estoqueMinimo?: number | undefined;
    precoVenda?: number | undefined;
    ncm?: string | undefined;
    cest?: string | undefined;
    cfop?: string | undefined;
    origem?: number | undefined;
    csosn?: string | undefined;
    cstICMS?: string | undefined;
    cstPIS?: string | undefined;
    cstCOFINS?: string | undefined;
    pICMS?: number | undefined;
    pPIS?: number | undefined;
    pCOFINS?: number | undefined;
    unidadeComercial?: string | undefined;
    gtin?: string | undefined;
    fornecedorId?: string | null | undefined;
    codigoFornecedor?: string | null | undefined;
    fatorConversao?: number | null | undefined;
    operacaoConversao?: "MULTIPLICAR" | "DIVIDIR" | null | undefined;
}, {
    nome?: string | undefined;
    tipo?: "INSUMO" | "PRODUTO_ACABADO" | "INSUMO_PRODUTO" | undefined;
    unidadeMedida?: "KG" | "G" | "L" | "ML" | "UN" | "CX" | "PCT" | undefined;
    custoUnitario?: number | undefined;
    categoriaId?: string | null | undefined;
    estoqueMinimo?: number | undefined;
    precoVenda?: number | undefined;
    ncm?: string | undefined;
    cest?: string | undefined;
    cfop?: string | undefined;
    origem?: number | undefined;
    csosn?: string | undefined;
    cstICMS?: string | undefined;
    cstPIS?: string | undefined;
    cstCOFINS?: string | undefined;
    pICMS?: number | undefined;
    pPIS?: number | undefined;
    pCOFINS?: number | undefined;
    unidadeComercial?: string | undefined;
    gtin?: string | undefined;
    fornecedorId?: string | null | undefined;
    codigoFornecedor?: string | null | undefined;
    fatorConversao?: number | null | undefined;
    operacaoConversao?: "MULTIPLICAR" | "DIVIDIR" | null | undefined;
}>;
export type CriarProdutoInput = z.infer<typeof CriarProdutoSchema>;
export type AtualizarProdutoInput = z.infer<typeof AtualizarProdutoSchema>;
//# sourceMappingURL=produtos.d.ts.map